[workspace]
members = [
    "crates/cli",
    "crates/core",
    "crates/entity",
    "crates/migration",
    "crates/server",
    "crates/test"
]
default-members = ["crates/cli"]

[workspace.dependencies]
async-graphql = { version = "5.0.10", features = ["chrono", "decimal", "tracing"] }
async-trait = "0.1.71"
chrono = { version = "0.4.26" }
dotenv = "0.15.0"
pxid = { version = "0.1.3" }
serde = { version = "1.0.171" }
serde_json = { version = "1.0.100" }
tokio = { version = "1.29.1", features = ["rt", "macros"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.15"
url = { version = "2.4.0", features = ["serde"] }
